language: php
matrix:
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: nightly
      env: PHP_CS_FIXER_IGNORE_ENV=1
  fast_finish: true
  allow_failures:
    - php: nightly
before_install: phpenv config-rm xdebug.ini || true
install: make install
script: scripts/travis
after_script: scripts/travis-after
env:
  global:
    - ELOQUENT_PUBLISH_VERSION=7.3
